[tool.poetry]
name = "data_filters"
version = "0.1.5"
description = "data filtration libray for the modelEAU research group"
authors = ["Jean-David Therrien <jeandavidt@gmail.com>"]
license = "All rights reserved modelEAU"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = "^1.8.0"
ipykernel = "^6.13.0"
nbformat = "^5.3.0"
ipython = "^8.2.0"
plotly = "^5.7.0"
pandas = "^1.4.2"
PyYAML = "^6.0"
pydantic = "^1.9.0"
dash = "^2.3.1"
numba = "^0.56.4"
scikit-learn = "^1.3.0"

[tool.poetry.dev-dependencies]
mypy = "^0.942"
flake8 = "^4.0.1"
pytest = "^7.1.2"
types-PyYAML = "^6.0.7"
black = "^22.3.0"
pre-commit = "^2.19.0"

[tool.poetry.group.dev.dependencies]
yelp-gprof2dot = "^1.2.0"
snakeviz = "^2.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
